### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by robinandeer**
Logo inspired by Watchdogs (the game) ^^

What do you think?

### CODE REVIEW

**Comment by robinandeer** [comment]
btw, the failing Travis test is just because there's actually no Travis config present in this branch :sweat_smile:

As soon as we start merging PRs and rebasing it will go away!

**Comment by robinandeer** [comment]
Can't wait no more - I am the design dictator anyways :smirk:

**Comment by ingkebil** [comment]
belated :+1:

**Comment by robinandeer** [comment]
Now I feel better :relieved:

**Pull request merged**
