### PR TITLE
Config

### PR DESCRIPTION
**Pull request by robinandeer**
In response to #1 I've created a class that can act as a unified interface to accessing nested config values.

```python
>>> from cghq.config import Config
>>> config = Config()
>>> config.get('meta.server_id')
'clinical-preproc'
>>> config
{'meta': {'server_id': 'clinical-preproc'}}
```

:question: I'm still thinking about whether to let the class handle the location of the actual config file or if that is the responsibility of the script using the class. If the latter then the class should just accept a file handle which makes it more flexible.

EDIT: OK I definitely think now that the class shouldn't care about the storage of the config file. It makes a lot more sense that a simple wrapper function concerns itself with that part of the implementation :smiley:

### CODE REVIEW

**Comment by robinandeer** [comment]
I will write some tests. I hope that will make it clear what scope the Config class should be restricted to.

**Comment by ingkebil** [comment]
I'm slightly disappointed this didn't involve somekind of apparel :/
But yay for coverage tracking!

**Comment by ingkebil** [comment]
And perfect with the config example.
I'll have a look at how you guys did the logging and integrate both of those.

**Comment by robinandeer** [comment]
More experienced developers have insisted I simplify the config class interface and I will listen :smile:

**Pull request merged**
